### ISSUE TITLE
public available roadmap?

### ISSUE THREAD

**Issue by ghost** [florence-social/mastodon-fork#178]
Hi,

We are hosting a Florence instance and wonder if there is somewhere a public available roadmap with a timetable for this project?

New versions of Mastodon are published regularly and Florence seems to be already way behind in functionality terms. We fear that broken changes may be made upstream and that will really mess the whole thing up.

Is there this type of document available somewhere? Or can maybe share some insights about your plans regarding Florence?

The only infos I can find are pretty vague, see this public thread by @mal0ki: https://elekk.xyz/@maloki/102798564259202646

Thanks in advance,

**Comment by mal0ki** [comment]
Hey, sorry for a bit of delay on responding here, I saw it when you posted but I've been down with a nasty cold. 

As I wrote elsewhere today: 

Currently we try to keep some info here: https://github.com/florence-social/governance/projects/1 
it's not been super publicized because it's a test. 
There's a blog post coming today, which has been delayed a lot because I was both sick, and exhausted due to a medicine hickup (which took me forever to realize). We gave some other active members a break because they were exhausted too. 

I think things will start rolling soon, but I mainly need a hand with figuring out how to roll in the 3.0 stuff we want, and if we can "fix" the issue with 3.0 being incompatible with some earlier Mastodon version. 
I realize that 3.0 indicates breaking features, but I think it may have broken more than people expected it to.

**Comment by ghost** [comment]
Hello,

No worries for the delay, thanks for answering!
I'll keep checking this for updates, but I can't wait for a proper website to be setup and subscribe to the RSS feed.

BTW if you need any help regarding hosting, sysadmin tasks, etc, don't hesitate to ping us: https://clic2000.fr/en

Best,

**Comment by ghost** [comment]
As it seems Florence's Mastodon fork will not be maintained anymore, and I don't use it anyway, I'm closing this.
