### ISSUE TITLE
Version number causing compatibility issues

### ISSUE THREAD

**Issue by BlueRaccoonTech** [florence-social/mastodon-fork#99]
Hello!

So I recently moved the instance I run all of my bots on from Glitchsoc to Florence (as I wanted to check things out and maybe give a helping hand), and I noticed all of my bots stopped posting once I did. I was confused by this at first, but then I realized that what was going on was that Mastodon.py, the library that I used for my bots, was reporting that the version of Mastodon was too old - because the version was being reported as 0.0.1.0 and it was comparing it to vanilla Mastodon. 

I opened up an issue on the library's Github, halcy/Mastodon.py#177 , and I realized that the version being reported doesn't specify that it's a fork or anything, like how Glitchsoc does with its version number (where it'd be, say, version+glitch or something) - it's only reporting 0.0.1.0, and that seems to cause a problem for being able to verify version numbers (as there isn't a way to tell that it's not running vanilla Mastodon.)

**Comment by halcy** [comment]
Hi,

elaborating on this: The relevant issue on Mastodon.py is https://github.com/halcy/Mastodon.py/issues/177 . Version checking is implemented to allow programs to fail in a way that is sensible, rather than just "huh this broke somehow with a 404 / this somehow returned a different result", so I'm not really willing to just turn it off, but I'd still like mastodon.py to work with Florence out of the box (it does currently work, but you have to explicitly ask for version checking to be off).

I see a few different way to mitigate this:
* You could indicate somehow (maybe with an additional field in the instance API response, or by appending something to the version string) that the instance runs Florence so that version checking can be different in some way in that case, where different probably means "turned off" because maintaining one set of version numbers is already painful.
* I could just guesstimate that anything using a four number version is Florence and do the same as above. This seems like the least ideal solution.
* You could decouple the API returned version string from what Florence uses as version (i.e. return something starting with 2.9.0 if an API compatible with upstream 2.9.0 is provided, no matter what your own version is). This would be the cleanest variant that I think is possible (and is what glitch does, and pleromas mastodon API compat layer, as far as I know), and would be the variant I like best (obviously, since it would require no changes on my end), but is additional maint work for you.
* You and upstream could both introduce an additional field in the instance response that specifies API version. This would be even cleaner, but you'd have to get everybody on board.

**Comment by jhaye** [comment]
Hi, thanks for reporting!

I suppose indicating that a server runs Florence via the version string is the most feasible for now, because I imagine that we'd like to keep our versioning scheme.

In the long run though, having something in the API that indicates what server software is being used would probably be the best solution and I imagine other projects like Pleroma would be on board with that, as they are currently doing what I described on paragraph above.

**Comment by halcy** [comment]
One comment on this: Pleroma doesn't do QUITE the same thing - it does have its own versioning, but the version it reports via the API matches whatever the current supported mastodon API version is. The obvious advantage of having a separate version for the API is that things like this become a non-issue (and also, I think it makes a lot of sense to decouple the machine-readable version of the interface from the version of the software). The obvious downside is that it's harder to tell at a glance whether a given server supports some API feature or not.

Since you're using your own versioning scheme as well (and might break compatibility in any case - I don't really know your plans there), the latter is going to be a problem no matter what, which is why I think it would be okay if you reported 2.9.0+whatever via the API, and still have your actual version and website-displayed version be something else - though that would take some work, probably, and could be maintenance effort every time you pull a new upstream version.

This would make it so that: 1) it's still possible to see what version of the upstream API your API matches 2) if Florence implements some other stuff on top that would be good to have, it'd be easy to support both upstream and Florence behaviour correctly without too much work. This is still possible if you don't use the upstream version, of course, but once multiple versions of florence exist it'd make debugging issues with florence instances harder (though likely not by that much)

**Comment by clarfonthey** [comment]
So, I looked in the file and it appears that it didn't actually report that version anywhere besides in the footer on the page, but clearly I didn't look hard enough. I guess that I'll revert back to my original plan of maintaining both a Mastodon API version and a Florence-flavour version as well.

**Comment by clarfonthey** [comment]
I came up with a half-decent fix for this at #104.

Essentially, the API would expose three strings:
* `version` (Mastodon-equivalent version)
* `flavor_name` (in our case, `"florence"`)
* `flavor_version` (in our case, `"0.0.1.0"`)

**Comment by mal0ki** [comment]
Did we need to discuss it further with them folx we mentioned elsewhere?
